#服务器配置
server:
  port: 8088
  servlet:
    context-path: /wechatgate

spring:
  application:
    name: wechat-gate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

db:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    jdbc-url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    password: 1234567

#redis
redis:
  sentinel:
    master: localhost:6379
    passwd: 123456

#微信配置
wechat:
  token: testfork
  access_token:
    #获取access_token请求URL
    url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
